- hosts: webservers
  gather_facts: no

  vars:
    root_dir: /var/www/rssagregator/
    repo: https://github.com/krokojabba/frontend-project-11.git

  tasks:
    - name: install packages
      ansible.builtin.apt:
        name:
          - nginx
          - git
          - nodejs
          - npm
        state: latest
        update_cache: yes
      become: yes
      tags: install

#    - name: Set authorized key taken from file
#      ansible.posix.authorized_key:
#        user: kroko
#        state: present
#        key: "{{ lookup('file', '/home/kroko/.ssh/id_ed25519.pub') }}"
#      tags: install

    - name: clone repo
      ansible.builtin.git:
        repo: "{{ repo }}"
        dest: ~/project
      tags: install

    - name: install project
      ansible.builtin.command: npm ci
      args:
        chdir: ~/project/
      tags: install

    - name: build project
      ansible.builtin.shell: NODE_ENV=production npx webpack
      args:
        chdir: ~/project/
      tags: install

    - name: update nginx project config in sites-available
      ansible.builtin.template:
        src: files/rssagregator.conf
        dest: /etc/nginx/sites-available/rssagregator.conf
      notify:
        - restart nginx
      become: yes
      tags: update

    - name: create a symbolic link to sites-enabled
      ansible.builtin.file:
        src: /etc/nginx/sites-available/rssagregator.conf
        dest: /etc/nginx/sites-enabled/rssagregator.conf
        state: link
      notify:
        - restart nginx
      become: yes
      tags: update

    - name: delete default server
      ansible.builtin.file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      notify:
        - restart nginx
      become: yes
      tags: update

    - name: create project directory if it does not exist
      ansible.builtin.file:
        path: "{{root_dir}}"
        state: directory
      become: yes
      tags: update

    - name: update content
      ansible.builtin.copy:
        src: files/index.html
        dest: "{{root_dir}}/index.html"
      become: yes
      tags: update

  handlers:
    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded
      become: yes
