- hosts: webservers
  gather_facts: no

  vars:
    root_dir: /home/kroko/rssagregator
    repo: https://github.com/krokojabba/frontend-project-11.git

  tasks:
    #- name: Install the gpg key for nodejs LTS
    #  apt_key:
    #    url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
    #    state: present
    #  become: yes
    #  tags: packages

    #- name: Install the nodejs LTS repos
    #  apt_repository:
    #    repo: "deb https://deb.nodesource.com/node_{{ NODEJS_VERSION }}.x jammy main"
    #    state: present
    #    update_cache: yes
    #  become: yes
    #  tags: packages
    - name: add nodejs 21.x
      ansible.builtin.shell: "curl -fsSL https://deb.nodesource.com/setup_21.x | bash"
      become: yes
      tags: packages

    - name: install packages
      ansible.builtin.apt:
        name:
          - nginx
          - git
          - nodejs
          - make
        state: latest
        update_cache: true
      become: yes
      tags: packages

    - name: Change permissions for home dir
      ansible.builtin.file:
        path: /home/kroko
        mode: 0755
      become: yes
      tags: repo

    - name: create project directory if it does not exist
      ansible.builtin.file:
        path: "{{root_dir}}"
        state: directory
        mode: 0755
      #become: yes
      tags: repo

    - name: clone repo
      ansible.builtin.git:
        repo: "{{ repo }}"
        dest: "{{ root_dir }}"
        force: yes
      #become: yes
      tags: repo

    - name: install and build project
      make:
        chdir: "{{ root_dir }}"
        target: "{{ item }}"
      loop:
        - install
        - build
      tags: build

    #- name: build project
    #  ansible.builtin.shell: NODE_ENV=production npx webpack
    #  args:
    #    chdir: "{{ root_dir }}"
    #  tags: build

    - name: update nginx project config in sites-available
      ansible.builtin.template:
        src: files/rssagregator.conf
        dest: /etc/nginx/sites-available/rssagregator.conf
      notify:
        - restart nginx
      become: yes
      tags: nginx

    - name: create a symbolic link to sites-enabled
      ansible.builtin.file:
        src: /etc/nginx/sites-available/rssagregator.conf
        dest: /etc/nginx/sites-enabled/rssagregator.conf
        state: link
      notify:
        - restart nginx
      become: yes
      tags: nginx

    - name: delete default server
      ansible.builtin.file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      notify:
        - restart nginx
      become: yes
      tags: nginx

    #- name: copy demo content
    #  ansible.builtin.template:
    #    src: files/index.html
    #    dest: "{{ root_dir }}/dist/index.html"
    #  notify:
    #    - restart nginx
    #  become: yes
    #  tags: demo_content

  handlers:
    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded
      become: yes
